version: '2.3'

services:

  nedockerschedular:
    image: labizbille/nedockerschedular:1.0.0.20
    ports:
      - 8082:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/appSettings.jobSchedules.json:/app/appSettings.jobSchedules.json


